[package]
name = "iota_lz4_udp"
version = "0.1.0"
authors = ["Alex6323 <Al3k5@protonmail.com>"]
edition = "2018"

[dependencies]
lz4 = "1.23.1"
lazy_static = "1.3.0"
regex = "1.1.6"
rand = "0.6.5"

[dev-dependencies]
rayon = "1.0.3"
